use escoba15_engine::Lang;

#[allow(dead_code)]
pub struct Strings {
    pub title: &'static str,
    pub quit_hint: &'static str,
    pub choose_lang: &'static str,
    pub game_mode: &'static str,
    pub mode_hvh: &'static str,
    pub mode_ai_easy: &'static str,
    pub mode_ai_medium: &'static str,
    pub mode_ai_hard: &'static str,
    pub choose_mode: &'static str,
    pub player_1_prompt: &'static str,
    pub player_2_prompt: &'static str,
    pub your_name_prompt: &'static str,
    pub vs: &'static str,
    pub first_to_15: &'static str,
    pub round: &'static str,
    pub round_results: &'static str,
    pub your_hand: &'static str,
    pub pick_card: &'static str,
    pub invalid_choice: &'static str,
    pub no_captures: &'static str,
    pub card_dropped: &'static str,
    pub possible_captures: &'static str,
    pub drop_option: &'static str,
    pub back_option: &'static str,
    pub choose_action: &'static str,
    pub going_back: &'static str,
    pub captured: &'static str,
    pub escoba: &'static str,
    pub table_empty: &'static str,
    pub table_cards: &'static str,
    pub score_cards: &'static str,
    pub score_oros: &'static str,
    pub score_siete_velo: &'static str,
    pub score_sevens: &'static str,
    pub score_escobas: &'static str,
    pub score_round_total: &'static str,
    pub cumulative: &'static str,
    pub wins_game: &'static str,
    pub thinking: &'static str,
    pub plays: &'static str,
    pub drops: &'static str,
    pub swept_table: &'static str,
    pub goodbye: &'static str,
    pub enter_number: &'static str,
    pub turn: &'static str,
    pub ai_easy: &'static str,
    pub ai_medium: &'static str,
    pub ai_hard: &'static str,
}

pub const ES: Strings = Strings {
    title: "ESCOBA DEL 15",
    quit_hint: "Escribe 'q' en cualquier momento para salir.",
    choose_lang: "Idioma / Language:",
    game_mode: "Modo de juego:",
    mode_hvh: "Humano vs Humano",
    mode_ai_easy: "Humano vs IA (Facil)",
    mode_ai_medium: "Humano vs IA (Medio)",
    mode_ai_hard: "Humano vs IA (Dificil)",
    choose_mode: "Elige modo [1-4]: ",
    player_1_prompt: "Nombre jugador 1 (Enter para 'Jugador 1'): ",
    player_2_prompt: "Nombre jugador 2 (Enter para 'Jugador 2'): ",
    your_name_prompt: "Tu nombre (Enter para 'Jugador'): ",
    vs: "vs",
    first_to_15: "Primero en llegar a 15 puntos gana. A jugar!",
    round: "RONDA",
    round_results: "RESULTADOS RONDA",
    your_hand: "Tu mano:",
    pick_card: "Elige una carta de tu mano [numero]: ",
    invalid_choice: "Opcion invalida.",
    no_captures: "No hay capturas posibles con {}. Carta al mesa.",
    card_dropped: "Carta al mesa.",
    possible_captures: "Capturas posibles con {} (val:{}):",
    drop_option: "Soltar carta (no capturar)",
    back_option: "Volver (elegir otra carta)",
    choose_action: "Elige [numero, 0 para soltar, b para volver]: ",
    going_back: "Volviendo a elegir carta...",
    captured: "Capturado: {}",
    escoba: "*** ESCOBA! *** Mesa limpia!",
    table_empty: "Mesa: [vacia]",
    table_cards: "Cartas en mesa:",
    score_cards: "Cartas:",
    score_oros: "Oros:",
    score_siete_velo: "7 de Oros:",
    score_sevens: "Sietes:",
    score_escobas: "Escobas:",
    score_round_total: "Total ronda:",
    cumulative: "Acumulado:",
    wins_game: "GANA LA PARTIDA!",
    thinking: "esta pensando",
    plays: "juega:",
    drops: "suelta {} en la mesa.",
    swept_table: "*** ESCOBA! *** {} barrio la mesa!",
    goodbye: "Gracias por jugar! Hasta luego!",
    enter_number: "Ingresa un numero valido.",
    turn: "Turno de {}",
    ai_easy: "IA (Facil)",
    ai_medium: "IA (Medio)",
    ai_hard: "IA (Dificil)",
};

pub const EN: Strings = Strings {
    title: "ESCOBA DEL 15",
    quit_hint: "Type 'q' at any prompt to quit.",
    choose_lang: "Idioma / Language:",
    game_mode: "Game mode:",
    mode_hvh: "Human vs Human",
    mode_ai_easy: "Human vs AI (Easy)",
    mode_ai_medium: "Human vs AI (Medium)",
    mode_ai_hard: "Human vs AI (Hard)",
    choose_mode: "Choose mode [1-4]: ",
    player_1_prompt: "Player 1 name (Enter for 'Player 1'): ",
    player_2_prompt: "Player 2 name (Enter for 'Player 2'): ",
    your_name_prompt: "Your name (Enter for 'Player'): ",
    vs: "vs",
    first_to_15: "First to 15 points wins. Let's go!",
    round: "ROUND",
    round_results: "ROUND RESULTS",
    your_hand: "Your hand:",
    pick_card: "Pick a card from your hand [number]: ",
    invalid_choice: "Invalid choice.",
    no_captures: "No captures possible with {}. Card dropped to table.",
    card_dropped: "Card dropped to table.",
    possible_captures: "Possible captures with {} (val:{}):",
    drop_option: "Drop card (no capture)",
    back_option: "Back (pick a different card)",
    choose_action: "Choose [number, 0 to drop, b to go back]: ",
    going_back: "Going back to card selection...",
    captured: "Captured: {}",
    escoba: "*** ESCOBA! *** Table swept clean!",
    table_empty: "Table: [empty]",
    table_cards: "Table cards:",
    score_cards: "Cards:",
    score_oros: "Oros:",
    score_siete_velo: "7 de Oros:",
    score_sevens: "Sevens:",
    score_escobas: "Escobas:",
    score_round_total: "Round total:",
    cumulative: "Cumulative:",
    wins_game: "WINS THE GAME!",
    thinking: "is thinking",
    plays: "plays:",
    drops: "drops {} on the table.",
    swept_table: "*** ESCOBA! *** {} swept the table!",
    goodbye: "Thanks for playing! Hasta luego!",
    enter_number: "Please enter a valid number.",
    turn: "{}'s turn",
    ai_easy: "AI (Easy)",
    ai_medium: "AI (Medium)",
    ai_hard: "AI (Hard)",
};

pub fn for_lang(lang: Lang) -> &'static Strings {
    match lang {
        Lang::Es => &ES,
        Lang::En => &EN,
    }
}
